#! /bin/bash

### BEGIN INIT INFO
# Provides: mmonit
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: mmonit
### END INIT INFO

set -e

DAEMON=/usr/local/mmonit/bin/mmonit
MMONIT_SERVER_CONF=/etc/mmonit/server.xml
NAME="mmonit"
DESC="mmonit"
MONIT_HOME_DIR=/usr/local/mmonit
PID_DIR=/var/run
PID_FILE=$PID_DIR/mmonit.pid
ENABLED=0

test -x $DAEMON || exit 0

if [ -e /etc/default/mmonit ]; then
	. /etc/default/mmonit
fi

test "$ENABLED" != "0" || exit 0

umask 022

. /lib/lsb/init-functions

check_mmonit_config() {
  $DAEMON -c $MMONIT_SERVER_CONF -r $MONIT_HOME_DIR -t
}

start_mmonit() {
  $DAEMON -c $MMONIT_SERVER_CONF -r $MONIT_HOME_DIR -p $PID_DIR start
}

stop_mmonit() {
  $DAEMON -c $MMONIT_SERVER_CONF -r $MONIT_HOME_DIR -p $PID_DIR stop 
}

case "$1" in
  start)
    echo -n "Starting $DESC: "
    check_mmonit_config
    start_mmonit
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    stop_mmonit
    echo "$NAME."
    ;;
  restart)
    echo -n "Restarting $DESC: "
    check_mmonit_config
    stop_mmonit || true
    sleep 1
    start_mmonit
    echo "$NAME."
    ;;
 status)
    status_of_proc -p $PID_FILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/mmonit {start|stop|restart|status}"
    exit 1
esac

exit 0
